source "https://rubygems.org"

gem "github-pages", "~> 232", group: :jekyll_plugins

# If you have any plugins, put them here!
#group :jekyll_plugins do
#end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 2.0.6"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.2.0", :install_if => Gem.win_platform?

# Vulnerability  fixes
gem "nokogiri", "~> 1.19.3"
gem "rexml", "~> 3.4.2"
gem "commonmarker", ">= 0.23.10"
gem "activesupport", "~> 7.2.3.1"
gem "faraday", ">= 2.14.3"
gem "json", ">= 2.19.2"
gem "addressable", ">= 2.9.0"

# Fix for when using Ruby 3 - webrick no longer installed w/ Ruby 3
gem "webrick", "~> 1.8"
# Fix for Ruby >= 3.4 - csv no longer part of default gems
gem "csv", "~> 3.3.5"
# Fix for warning in Ruby 3.4 - fiddle won't be a default gem from Ruby 4.0.0
gem "fiddle", "~> 1.1.8"
# Fix Jekyll warning to use faraday-retry with faraday >= v2.0
gem "faraday-retry", "~> 2.4"
